# Faster builds
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx1024m -XX:-UseGCOverheadLimit -Dfile.encoding=UTF-8

# FoxLoader properties
foxloader.version=1.3.3
foxloader.lastReIndevTransformerChanges=1.3.0
# https://www.jitpack.io/#com.fox2code/FoxLoader

# ReIndev properties
reindev.clientUrl=https://cdn.fox2code.com/files/reindev_2.8.1_06.jar
reindev.serverUrl=https://cdn.fox2code.com/files/reindev_2.8.1_06_server.jar
reindev.clientJar=reindev_2.8.1_06.jar
reindev.serverJar=reindev_2.8.1_06_server.jar
reindev.clientSHA256Sum=686a331fe90143617afeeb1f78a41776def6e22aaf2e62ff3bbb3b64c43f33d9
reindev.serverSHA256Sum=16ef1057ba66beb8dfbd5fb7d5242475dcfaae79fe403449199af834deced837
reindev.version=2.8.1_6
reindev.version.allowFrom=2.8.1_5

# NSSS properties
nsss.clientUrl=https://www.dropbox.com/scl/fi/s7yg08ukwih3ixkbw3qhg/a1.1.11_111.jar?rlkey=yvlg58xjyz51bj7utoilc7zjt&st=ura2dw51&dl=1
nsss.serverUrl=https://www.dropbox.com/scl/fi/i548kdc0dno46uw3whhk5/a1.1.11_111_server.jar?rlkey=ca8bmsd0uz53nn14to7o5m794&st=ijyv239j&dl=1
nsss.clientJar=a1.1.11_111.jar
nsss.serverJar=a1.1.11_111_server.jar
nsss.clientSHA256Sum=78994254247f3c10c791fede56562f12f73001fb378123cbb2dcacd17a4220aa
nsss.serverSHA256Sum=1dfae499c1f1df1f6aae816c1f2d00d6f106a3beb8d79667a3c536d3078e10a0
nsss.version=1.1.11_111
nsss.version.allowFrom=1.1.11_111


#Spark properties
spark.dependency=maven.modrinth:spark:1.10.65-fabric
spark.version=1.10.65

#VineFlower properties
vineflower.dependency=org.vineflower:vineflower:1.10.1
