pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'ReIndev+NSSS+FoxLoader'
include 'client'
include 'server'
include 'clientNSSS'
include 'serverNSSS'
include 'common'
include 'final'
include 'betacraft'
include 'dev'
include 'api'
include 'dev11'

